import type { IconSvgElement } from "@hugeicons/react"
import {
  Analytics01Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  AtIcon,
  CloudIcon,
  Coins01Icon,
  Copy01Icon,
  Delete02Icon,
  Download01Icon,
  Exchange01Icon,
  Globe02Icon,
  Home01Icon,
  InboxIcon,
  JusticeScale01Icon,
  Link01Icon,
  Menu01Icon,
  Message01Icon,
  MoreVerticalIcon,
  News01Icon,
  Pin02Icon,
  Rocket01Icon,
  SentIcon,
  Settings01Icon,
  Share08Icon,
  Store01Icon,
  Tick02Icon,
  TransactionHistoryIcon,
  Upload01Icon,
  ViewOffIcon,
  Wallet01Icon,
} from "@hugeicons/core-free-icons"

export const appIcons = {
  home: Home01Icon,
  icpverse: Globe02Icon,
  send: ArrowUp01Icon,
  deposit: ArrowDown01Icon,
  withdraw: ArrowUpRight01Icon,
  menu: Menu01Icon,
  shop: Store01Icon,
  wallet: Wallet01Icon,
  swap: Exchange01Icon,
  launch: Rocket01Icon,
  username: AtIcon,
  analytics: Analytics01Icon,
  history: TransactionHistoryIcon,
  bucket: CloudIcon,
  governance: JusticeScale01Icon,
  settings: Settings01Icon,
  blog: News01Icon,
  hide: ViewOffIcon,
  copy: Copy01Icon,
  check: Tick02Icon,
  share: Share08Icon,
  pin: Pin02Icon,
  back: ArrowLeft01Icon,
  delete: Delete02Icon,
  download: Download01Icon,
  upload: Upload01Icon,
  empty: InboxIcon,
  community: Message01Icon,
  icpay: Coins01Icon,
  chatSend: SentIcon,
  chatBack: ArrowLeft01Icon,
  chatMore: MoreVerticalIcon,
  chatPin: Pin02Icon,
  chatDelete: Delete02Icon,
  chatCopy: Copy01Icon,
  chatShare: Link01Icon,
} as const satisfies Record<string, IconSvgElement>

export type AppIconName = keyof typeof appIcons
