export const appIcons = {
  home: "/images/icons8/icons8-safe-48.png",
  icpverse: "/images/icons8/icons8-merchant-account-48.png",
  send: "/images/icons8/icons8-online-money-transfer-48.png",
  menu: "/images/icons8/icons8-squared-menu-48.png",
  shop: "/images/navballcenter/icons8-shop-48.png",
  wallet: "/images/icons8/icons8-card-wallet-48.png",
  swap: "/images/icons8/icons8-money-circulation-48.png",
  launch: "/images/icons8/icons8-idea-bank-48.png",
  username: "/images/icons8/icons8-at-sign-48.png",
  analytics: "/images/icons8/icons8-dividends-48.png",
  history: "/images/icons8/icons8-payment-history-48.png",
  bucket: "/images/icons8/icons8-money-box-48.png",
  settings: "/images/icons8/icons8-gear-48.png",
  blog: "/images/icons8/icons8-webpage-48.png",
  hide: "/images/icons8/icons8-hide-48.png",
  copy: "/images/icons8/icons8-shortlist-48.png",
  check: "/images/icons8/icons8-approval-48.png",
  share: "/images/icons8/icons8-share-48.png",
  pin: "/images/icons8/icons8-pin-48.png",
  back: "/images/icons8/icons8-back-arrow-48.png",
  delete: "/images/icons8/icons8-trash-can-48.png",
  download: "/images/icons8/icons8-download-48.png",
  upload: "/images/icons8/icons8-add-48.png",
  empty: "/images/icons8/icons8-bounced-check-48.png",
  community: "/images/icons8/MESSAGING/icons8-chat-bubble-48.png",
  chatSend: "/images/icons8/MESSAGING/icons8-email-send-48.png",
  chatBack: "/images/icons8/icons8-back-arrow-48.png",
  chatMore: "/images/icons8/MESSAGING/icons8-more-48.png",
  chatPin: "/images/icons8/MESSAGING/icons8-pin-code-48.png",
  chatDelete: "/images/icons8/MESSAGING/icons8-delete-message-48.png",
  chatCopy: "/images/icons8/MESSAGING/icons8-copy-link-48.png",
  chatShare: "/images/icons8/MESSAGING/icons8-add-link-48.png",
} as const

export type AppIconName = keyof typeof appIcons
