[package]
name = "icpay-wallet"
version = "1.0.0"
description = "ICPay desktop wallet"
authors = ["ICPay"]
edition = "2021"

[lib]
name = "icpay_wallet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
